---
version: 2
executorType: docker
containerInfo:
  - image: alpine:latest
    cmd: ["apk","add","--update","curl",";","sleep", "180"]
stages:
  build:
    workDir: ~/
    steps:
#       - type: checkout
      - type: shell
        shell: /bin/sh
        name: Install Docker Client
        command: |
          mkditr -p /root/my-project
          echo "test"
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/

          curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x  /usr/bin/docker-compose

      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        shell: /bin/sh
        command: |
          docker --version
          docker run ubuntu /bin/echo "Hello world"
