---
version: 2
executorType: machine
stages:
  build:
    workDir: ~/my-project
    steps:
      - type: checkout
      - type: shell
        name: Verify Docker Works
        command: |
          docker version
          docker build -t myp .
          docker run myp /bin/true
          mkdir images
          docker save -o images/myp myp
      - type: artifacts-store
        path: images/myp
        destination: prefixer
