---
version: 2
executorType: docker
machine:
  python:
    version: 2.7
test:
  override:
    - bash -c 'until [ -f ./fin ] ; do echo "." ; sleep 2 ; done &'
    - sleep 10
    - touch fin
containerInfo:
  - image: python:2.7.12
stages:
  build:
    workDir: /home/ubuntu/canary-python
    environment:
      - FOO: "bar"
    steps:
      - type: checkout
      - type: shell
        command: echo "When I say Foo... You say $FOO"
