---
version: 2
executorType: machine
stages:
  build:
    workDir: ~/my-project
    steps:
      - type: checkout
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run ubuntu /bin/echo "Hello world"
